quarkus.application.name=ecommerce-garrafas
quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=topicos1
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerceTp1

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

mp.jwt.verify.publickey.location=token/publicKey.pem
mp.jwt.verify.issuer=topicos_1
smallrye.jwt.sign.key.location=token/privateKey.pem

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,PUT,POST,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=Authorization,Content-Disposition
quarkus.http.cors.access-control-allow-credentials=true

seaweedfs.master.url=http://localhost:9333
seaweedfs.request-timeout-ms=10000

%dev.seaweedfs.devservice.enabled=true